packages:
  - packages/*
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - unrs-resolver
patchedDependencies:
  semantic-release-pnpm: patches/semantic-release-pnpm.patch
